@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzI3NzIzMDJ9.xOPBA8NoARB9Y3TsjDUfAUASrGyaNBM3fAYo1aNnXRM


### Breweries Index
GET http://localhost:3000/breweries


### Breweries Show
GET http://localhost:3000/breweries/2.json


#-----------------------------------------------------------

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Tere",
  "email": "tere@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}


#-----------------------------------------------------------

### Create a Tour

POST http://localhost:3000/tours
Authorization: Bearer {{jwt}}
Content-Type: application/json

{ 
  "brewery_id": 3
}

### Show Tour
GET http://localhost:3000/tours/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Destroy Tour
DELETE http://localhost:3000/tours/3.json
Authorization: Bearer {{jwt}}
Content-Type: application/json



#-----------------------------------------------------------



### Add Brewery/Tour

POST http://localhost:3000/breweries_tours
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "brewery_id": 2,
  "tour_id": 2
}

### Tours Index
GET http://localhost:3000/breweries_tours
