@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzI0NTg5MzZ9.B6mxQdFk--8XKpfg0zwlHbRVwEQS7tTtVkbxjRHA35I


### Breweries Index
GET http://localhost:3000/breweries


### Breweries Show
GET http://localhost:3000/breweries/2.json


#-----------------------------------------------------------

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Johnny",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}


#-----------------------------------------------------------

### Create a Tour

POST http://localhost:3000/breweries_tours/1.json

Content-Type: application/json

{
  "breweries_id": 2,
  "tours_id": 1
}


### Tours Index
GET http://localhost:3000/breweries_tours/1
