User.create!([
  {name: "Johnny", email: "test@test.com", password_digest: "$2a$12$jphPHUh6TKVzNSDquo6k1.6pvn1Su3BHk/S7ERPFoCy/SwvarX5Bq", image_url: nil},
  {name: "Tere", email: "tere@test.com", password_digest: "$2a$12$gu8uVO44RGemZ3URsjfn7ePHUHJwfBMdeRMFPkfkHkag3uwPQm1vK", image_url: nil},
  {name: "Tio", email: "tio@test.com", password_digest: "$2a$12$ukj92Jnko1IzQ1JKTvUgkOZWeeg2kuQ5c2V7m4AEvM5oS1xwk1Mfy", image_url: nil},
  {name: "Jess", email: "jess@test.com", password_digest: "$2a$12$KdCvH1UiTaaUnhYREzwUQe.QYXn.7fHL7PT53rc0s9sblyu.nKfSW", image_url: nil},
  {name: "me", email: "me@test.com", password_digest: "$2a$12$TVL3xtjmQkELzkDa95Ql7ODWT089xMO.jkWOabhSFPxZa2Fov0.b.", image_url: nil},
  {name: "Jocie", email: "Jocie@test.com", password_digest: "$2a$12$yMyZCcJAsmnHV7O/phEIve8Xz.yxNIdL.43feONUIXX7vnvF1UwiS", image_url: nil},
  {name: "tio b", email: "tiob@test.com", password_digest: "$2a$12$Cy1m.6f/AS5FSXXg4xo2POza4Suu0bHLg1PK1h3vFsuXDpiMOXwiK", image_url: nil},
  {name: "Jocie", email: "jocie@test.com", password_digest: "$2a$12$tUWtM8MgW9y5bmbVWjkzm.x6.USVMr0jeKjvtb2v8fA4BFZ59SrQG", image_url: nil},
  {name: "mel", email: "mel@test.com", password_digest: "$2a$12$pRczeNH8lsNAafD4Xjo9ruHCYN2XGGBlzVto2Ok.J8IuqDEugW9qu", image_url: nil},
  {name: "Adam F", email: "adam@test.com", password_digest: "$2a$12$zcmabp6cdYOACVTSimQPAuXFsnc.zO2zUN25wr1UFd3mL0ciYaIjW", image_url: nil},
  {name: "Julia P", email: "julia@test.com", password_digest: "$2a$12$ffAbwR/3VMwIeenBElwNr.eItDy.YvfdJtqm3uhuyqFqNTcIJ7apK", image_url: nil},
  {name: "sam", email: "sam@test.com", password_digest: "$2a$12$DaHWJLdg03RlsHD5RlYRfuzTzRrtmXRAmaumytamtalJxZES7V9f.", image_url: nil},
  {name: "Bill", email: "bill@test.com", password_digest: "$2a$12$vohgTP2.9y3YC.oDS3doBOCHNltQac/NfezUAVloiQ55o827THOlu", image_url: nil},
  {name: "tom", email: "tom@test.com", password_digest: "$2a$12$10Jz2bGhkSR.iIeQLZvuoeL7boWlVQToh93vJfcpERVrWHPl3RAS.", image_url: nil}
])
Tour.create!([
  {user_id: 8, name: "Anniversary"},
  {user_id: 9, name: "Birthday"},
  {user_id: 1, name: "My Birthday"},
  {user_id: 1, name: "Dallas Trip"},
  {user_id: 2, name: "Prom"},
  {user_id: 10, name: "Dallas Party"},
  {user_id: 2, name: "Vaca"},
  {user_id: 11, name: "Adams Bday"},
  {user_id: 1, name: "Wedding"},
  {user_id: 12, name: "Bday Bash"},
  {user_id: 1, name: "Easter"},
  {user_id: 1, name: "Hi"},
  {user_id: 13, name: "Bday Party"},
  {user_id: 10, name: "Easter"},
  {user_id: 14, name: "evans bash"}
])
BreweryTour.create!([
  {brewery_id: 2, tour_id: 8, user_id: nil},
  {brewery_id: 2, tour_id: 6, user_id: nil},
  {brewery_id: 2, tour_id: 6, user_id: nil},
  {brewery_id: 1, tour_id: 18, user_id: nil},
  {brewery_id: 3, tour_id: 6, user_id: 1},
  {brewery_id: 3, tour_id: 6, user_id: 1},
  {brewery_id: 9, tour_id: 20, user_id: 1},
  {brewery_id: 10, tour_id: 9, user_id: 1},
  {brewery_id: 11, tour_id: 22, user_id: 7},
  {brewery_id: 12, tour_id: 24, user_id: 8},
  {brewery_id: 14, tour_id: 17, user_id: 1},
  {brewery_id: 8, tour_id: 7, user_id: 1},
  {brewery_id: 15, tour_id: 42, user_id: 1},
  {brewery_id: 8, tour_id: 42, user_id: 1},
  {brewery_id: 17, tour_id: 42, user_id: 1},
  {brewery_id: 13, tour_id: 42, user_id: 1},
  {brewery_id: 16, tour_id: 42, user_id: 1},
  {brewery_id: 20, tour_id: 43, user_id: 1},
  {brewery_id: 20, tour_id: 42, user_id: 1},
  {brewery_id: 22, tour_id: 43, user_id: 1},
  {brewery_id: 23, tour_id: 43, user_id: 1},
  {brewery_id: 24, tour_id: 7, user_id: 1},
  {brewery_id: 25, tour_id: 7, user_id: 1},
  {brewery_id: 26, tour_id: 6, user_id: 1},
  {brewery_id: 3, tour_id: 46, user_id: 9},
  {brewery_id: 27, tour_id: 46, user_id: 9},
  {brewery_id: 8, tour_id: 46, user_id: 9},
  {brewery_id: 28, tour_id: 47, user_id: 1},
  {brewery_id: 29, tour_id: 47, user_id: 1},
  {brewery_id: 31, tour_id: 48, user_id: 10},
  {brewery_id: 33, tour_id: 48, user_id: 10},
  {brewery_id: 34, tour_id: 49, user_id: 10},
  {brewery_id: 35, tour_id: 49, user_id: 10},
  {brewery_id: 36, tour_id: 48, user_id: 10},
  {brewery_id: 37, tour_id: 48, user_id: 10},
  {brewery_id: 39, tour_id: 48, user_id: 10},
  {brewery_id: 40, tour_id: 50, user_id: 11},
  {brewery_id: 41, tour_id: 50, user_id: 11},
  {brewery_id: 42, tour_id: 51, user_id: 11},
  {brewery_id: 44, tour_id: 51, user_id: 11},
  {brewery_id: 45, tour_id: 51, user_id: 11},
  {brewery_id: 46, tour_id: 51, user_id: 11},
  {brewery_id: 18, tour_id: 52, user_id: 12},
  {brewery_id: 47, tour_id: 52, user_id: 12},
  {brewery_id: 48, tour_id: 53, user_id: 12},
  {brewery_id: 49, tour_id: 7, user_id: 1},
  {brewery_id: 50, tour_id: 55, user_id: 13},
  {brewery_id: 42, tour_id: 55, user_id: 13},
  {brewery_id: 51, tour_id: 56, user_id: 13},
  {brewery_id: 21, tour_id: 58, user_id: 14},
  {brewery_id: 53, tour_id: 59, user_id: 14}
])
Brewery.create!([
  {name: "Goose Island", address: "North Ave", description: "Great Vaierty of Beers"},
  {name: "Three Floyds", address: "5555 Indiana", description: "Best Location for all types of brews"},
  {name: "Orlando Brewing Partners", address: "1301 Atlanta Avenue, Orlando, FL, 32806", description: "orlandobrewing.com/"},
  {name: "Wedding", address: "1301 Atlanta Avenue, Orlando, FL, 32806", description: "orlandobrewing.com/"},
  {name: "TEST HI ", address: "1301 Atlanta Avenue, Orlando, FL, 32806", description: "orlandobrewing.com/"},
  {name: nil, address: ", , , ", description: nil},
  {name: nil, address: ", , , ", description: nil},
  {name: "BJ's Brewhouse - Millenia Mall", address: "4151 Conroy Road, Orlando, FL, 32839", description: "bjsrestaurants.com"},
  {name: "B. B. Rovers", address: "12636 Research Blvd., Austin, TX, 78759", description: "essentialaustin.com/bbrovers/"},
  {name: "North by Northwest Restaurant and Brewery", address: "10010 Capital Of TX Hwy N, Austin, TX, 78759", description: "nxnwbrew.com/"},
  {name: "Peckish Pig", address: "623 Howard Street, Evanston, IL, 60202", description: "thepeckishpig.com"},
  {name: "Dog and Duck Pub", address: "406 W 17th St, Austin, TX, 78701", description: "dogandduckpub.com/"},
  {name: "Cafe Tu Tu Tango", address: "8625 International Drive, Orlando, FL, 32839", description: "cafetututango.com/orlando/"},
  {name: "World of Beer - UCF", address: "3402 Technological Dr. Suite 201, Orlando, FL, 32817", description: "wobucf.com"},
  {name: "Hearts Homebrew/Orlando Home Brew Beer", address: "6190 Edgewater Drive, Orlando, FL, 32810", description: "heartshomebrew.com"},
  {name: "Redlight Redlight", address: "745 Bennett Rd, Orlando, FL, 32803", description: "myspace.com/theredlightredlight"},
  {name: "Underground Bluz", address: "12261 University Blvd, Orlando, FL, 32817", description: "ucf.undergroundbluz.com/"},
  {name: "Independence Brewing Co.", address: "3913 Todd Lane, No. 607, Austin, TX, 78744", description: "independencebrewing.com/"},
  {name: "Friendly Confines I", address: "435 N Alafaya Trl  , Orlando, FL, 32828", description: "myfriendlyconfines.com"},
  {name: "Tommy Nevin's Irish Pub", address: "1454 Sherman Ave, Evanston, IL, 60201", description: "tommynevins.com/"},
  {name: "Crown and Anchor Pub", address: "2911 San Jacinto Blvd, Austin, TX, 78705", description: ""},
  {name: "Billy's on Burnet", address: "2105 Hancock Dr., Austin, TX, 78756", description: ""},
  {name: "Central Market - South Austin", address: "4477 South Lamar, Austin, TX, 78745", description: "centralmarket.com/cm/cmLocation.jsp#Slamar"},
  {name: "Temperance Beer Company", address: "2000 Dempster Street, Evanston, IL, 60202", description: "temperancebeer.com"},
  {name: "Smylie Brothers Brewing Company", address: "1615 Oak Avenue, Evanston, IL, 60201", description: "smyliebros.com"},
  {name: "Pegasus City Brewery", address: "2222 Vantage St, Dallas, TX, 75207", description: "https://www.pegasuscitybrewery.com/"},
  {name: "Firkin and Kegler", address: "12850 Waterford Lakes Parkway , Orlando, FL, 32828", description: "firkinpubs.com"},
  {name: "Humperdinks/Big Horn Brewing -Dallas (Greenville)", address: "6050 Greenville Ave, Dallas, TX, 75206", description: "humperdinks.com/"},
  {name: "Ginger Man, The - Dallas", address: "2718 Boll Street, Dallas, TX, 75204", description: "gingermanpub.com/"},
  {name: "Tipperary Inn", address: "5815 Live Oak Street, Dallas, TX, 75214", description: "tippinn.com/"},
  {name: "Idle Rich Pub, The", address: "2614 McKinney Ave, Dallas, TX, 75204", description: "idlerichpub.com/"},
  {name: "Central Market -  Dallas", address: "5750 E. Lovers Lane, Dallas, TX, 75206", description: "centralmarket.com/"},
  {name: "Common Table, Common", address: "2917 Fairmount St., Dallas, TX, 75201", description: "thecommontable.com"},
  {name: "Mr. Dunderbak's", address: "2222 University Sq Mall, Tampa, FL, 33613", description: "dunderbaks.com"},
  {name: "World of Beer - Tampa Palms", address: "17004 Palm Pointe Drive, Tampa, FL, 33647", description: "tampapalms.wobusa.com"},
  {name: "Jester King Craft Brewery", address: "13005 Fitzhugh Rd., Austin, TX, 78736", description: "jesterkingbrewery.com"},
  {name: "Thirsty Planet Brewing", address: "11160 Circle Drive, Austin, TX, 78736", description: "thirstyplanet.net"},
  {name: "Zax Pints And Plates", address: "312 Barton Springs Rd., Austin, TX, 78704", description: "zaxaustin.com/"},
  {name: "Central Market - Austin", address: "4001 N. Lamar, Austin, TX, 78756", description: "centralmarket.com/"},
  {name: "Huss Brewing Company", address: "1520 Mineral Road, Tempe, AZ, 85283", description: "hussbrewing.com"},
  {name: "Blasted Barley Beer Co.", address: "404 S. Mill Ave. Ste 10, Tempe, AZ, 85281", description: "blastedbarley.com"},
  {name: "Yuengling Brewery - Tampa", address: "11111 N 30th St, Tampa, FL, 33612", description: "yuengling.com/"},
  {name: "Cigar City Brewing", address: "3924 W Spruce St, Suite A, Tampa, FL, 33612", description: "cigarcitybeer.com"},
  {name: "The Pub Tampa Bay", address: "2223 N. West Shore Blvd., Tampa, FL, 33607", description: "experiencethepub.com/tampa-bay"},
  {name: "Draught House Pub and Brewery", address: "4112 Medical Parkway, Austin, TX, 78741", description: "draughthouse.com/"},
  {name: "Opal Divine's Freehouse", address: "700 W 6th St, Austin, TX, 78701", description: "opaldivines.com/"},
  {name: "Beerland Texas", address: "711 1/2 Red River, Austin, TX, 78701", description: "beerlandtexas.com/"},
  {name: "New World Brewery", address: "1313 E. 8th Ave, Tampa, FL, 33605", description: ""},
  {name: "Binny's Beverage Depot - Skokie", address: "5100 Dempster St, Skokie, IL, 60077", description: "binnys.com"},
  {name: "Four Green Fields", address: "205 Platt Street, Tampa, FL, 33606", description: "fourgreenfields.com"},
  {name: "Fado Irish Pub", address: "214 W 4th Street, Austin, TX, 78701", description: "fadoirishpub.com/austin"},
  {name: "Scholz Garten", address: "1607 San Jacinto, Austin, TX, 78701", description: "scholzgarten.net/"},
  {name: "Mr. Dunderbaks - Bruce B Downs Blvd", address: "14929 Bruce B Downs Boulevard, Tampa, FL, 33613", description: "dunderbaks.com"}
])
